### ISSUE TITLE
PKCE improvements

### ISSUE THREAD

**Issue by tsoestini** [rapi-doc/RapiDoc#745]
I made a few improvements to the PKCE flow:

1. Addressed the outstanding TODO to add a dynamic `codeVerifier` and `codeChallenge`.

2. Improved the entropy for `state` and `nonce` (some OAuth servers do not accept only 7 characters).

3. Allow `x-client-id`, `x-client-secret`, `x-default-scopes`, and `x-receive-token-in` to be overridden for particular OAuth flows (many OAuth servers do not allow a single client to be configured for both client credentials and single page app at the same time).

4. Add an `x-pkce-only` extension, for the single page app configuration of PKCE, which doesn't use a client secret, and does not allow the header option.

The updated file is attached.

[security-scheme-template.zip](https://github.com/rapi-doc/RapiDoc/files/8616954/security-scheme-template.zip)

**Comment by mrin9** [comment]
you may consider to provide a Pull Request instead, that way I can review it faster

**Comment by tsoestini** [comment]
I had a bit of trouble figuring it out, so hopefully I did it right.

https://github.com/rapi-doc/RapiDoc/pull/746

**Comment by mrin9** [comment]
Hi,
Sorry to reply late on this. the reason for not really merging is due to usage of `window.crypto` as we would like to minimize our dependency on browser which will help us in achieving server side rendering. w.r.t other points I have addressed them in 33bbb5c4b405beb8fd5cdbcdbda57fe77a48444c which is based on your PR

- Improved the entropy for state and nonce (some OAuth servers do not accept only 7 characters).
- Allow x-client-id, x-client-secret, x-default-scopes, and x-receive-token-in to be overridden for particular OAuth flows 
- Add an x-pkce-only extension, for the single page app configuration of PKCE, which doesn't use a client secret, and does not allow the header option.

dynamic codeVerifier and codeChallenge is not included, this is not a must we can fallback on pre-set values

Thank you for your contribution !!!
