### ISSUE TITLE
Nested schemas dont show key name

### ISSUE THREAD

**Issue by avhen** [rapi-doc/RapiDoc#787]
Hello, 

first of all, thanks all for your project. is really amazing.

I have the following issue (or I think so) 
the schemas with nested objects / arrays dont show the key name.

(related to schema-tree.json)

how could I fix that?

I attach the how the problem looks like.
![image](https://user-images.githubusercontent.com/88343881/180293636-1f326ffb-ffaa-44dc-a3fc-0f184c71194a.png)

**Comment by mrin9** [comment]
can you provide me with a minimal spec where I can recreate this issue ?

**Comment by avhen** [comment]
Steps to reproduce:
Download the  rapidoc zip project from github (https://github.com/rapi-doc/RapiDoc/archive/refs/heads/master.zip)
run npm install
run npm build_windows

copy/use the builded rapidoc-min.js from dist folder into your site.

I made additional tests and I found if you use the cdn (https://unpkg.com/rapidoc/dist/rapidoc-min.js)  instead of the builded minified version the schema shows well.

I atached a minimal example with the compiled rapidoc-min.js
[dist.zip](https://github.com/rapi-doc/RapiDoc/files/9162784/dist.zip)

please let me known if you require anything else.

Thanks

**Comment by mrin9** [comment]
thanks for reporting the issue and sharing a test case.

This issue is introduced  due to a bad commit https://github.com/rapi-doc/RapiDoc/commit/39102928ca6809a0e7e881cc0ead86434c9d0b5a which got added after the stable release of `9.3.3`

We will be take another look at the issue later, for now it is best to use the `cdn version 9.3.3`

**Comment by mrin9** [comment]
this is now restored by removing the bad commit
