### ISSUE TITLE
Feature Request: Tag focused render-style option

### ISSUE THREAD

**Issue by officeSpacePirate** [rapi-doc/RapiDoc#797]
I've been demoing RapiDoc as a replacement for my team's API services and between the available `render-style` options, I think there is an opportunity for an easier layout. Many REST API doc tools have the scrolling functionality of RapiDoc `read`, but we like the `focused` option as it reduces page size and offers the option to collapse tags in the navigation. My suggestion is to create a new render-style that encapsulates the best of both worlds; you could change the current `focused` option to `focused-method` and add `focused-tag`.

In `focused-tag`, the scrollable view would include all operations under that tag as well as the tag description. If you are considering the `info-description-headings-in-navbar` feature, this could also be viewed as a page per top level nav item. In this `render-style`, the nav would auto-collapse / auto-expand nav trees based on which section is shown in the view. Within the selected nav tree, scrolling the page would also move the nav indicator as it does in `read` today.

This would provide a sort of "greatest hits" from the features you already provide. Curious to hear your thoughts 😃

**Comment by mrin9** [comment]
Here is what we think of the feature set
- breaking the spec based on tag is a good idea and I am sure there will be many of our users wanting that feature
- auto-collapse / auto-expand nav items is a big no no with our user base because
  - it creates a distraction when scrolling and searching for an item, auto collapsing and expansion is an annoyance 
  - it is possible to show three operations at a time on a larger screen, at this moment you will never get it right which one to expand and which to collapse as it becomes a personal preference which area of screen is more important
  - we did created an auto-expand/collapsing prototype, feedback from our users were against it
  - our UX team like to keep indirect actions to minimum. (Indirect action is when user take an action and due to which another part of the UI gets affected)

Having said that, breaking spec based on tag may have some good use cases but at the moment will not be good use of our time to develop it as it has a potential to create a big churn in our code-base. We will re-analyze our rendering modes when we plan for a major version change. However, I am open to take a PR

I will close this issue, you are welcome to create a pull request for the other mode you are suggesting, it can be a rudimentary effort too, at least it will help us demo it to our US team

**Comment by officeSpacePirate** [comment]
Thanks for the thorough response!

On the auto-collapse/auto-expand, I was imagining it being based on the scroll position in the nav as it works today in `read` render-style. The expand/collapse would not be based on new screen positioning system, but the one that already exists.

That aside, I'll take a look at the repo and see if I can pick up the gist quickly enough to start a branch. Only question I would have is how would you guys prefer to handle the value for `render-style`? Breaking change in a major release (all new intuitive naming) or one new value that's non-breaking (and maybe less intuitive)?

**Comment by mrin9** [comment]
> On the auto-collapse/auto-expand, I was imagining it being based on the scroll position in the nav as it works today in read render-style.

we do have people with different opinion about which one to highlight when multiple operations are in the view. should you consider, screen, top, center or bottom more important ? 

highlighting is still fine, but if you auto collapse and hide information based on scroll position, it will not be received uniformly  considering our current user base.

> how would you guys prefer to handle the value for render-style ?

you can pick a new value for the rendering style and new template to render it, 
this keeps rendering code decoupled and leads to better support and isolation of issues. Also we are sensitive to the final bundle size as we bundle the entire web-component in a single file.
