### ISSUE TITLE
bug: focused layout doesn't update hash route unless clicked twice

### ISSUE THREAD

**Issue by lrstanley** [rapi-doc/RapiDoc#805]
Using **9.3.3**, when using focused render mode, clicking navigation links on the sidebar, both the "active" status, and the hash route don't change until it is clicked twice, as shown below:

![](https://cdn.liam.sh/share/2022/08/chrome_4Yw5CM6Tpp.gif)

Reverting to **9.3.2**, this issue is not present when using `focused` render mode. Receive no errors in the console or similar.

Let me know if there is any further information I can provide.

**EDIT**: for some additional info, this is how I'm loading the component currently (inside of a Vue app):

```html
<!-- [...] -->
  <rapi-doc
    render-style="focused"
    spec-url="https://petstore.swagger.io/v2/swagger.json"
    show-header="false"
    show-info="true"
    show-method-in-nav-bar="as-colored-block"
    nav-item-spacing="relaxed"
    allow-authentication="false"
    allow-server-selection="false"
    allow-spec-url-load="false"
    allow-spec-file-load="false"
    allow-spec-file-download="false"
    allow-api-list-style-selection="false"
    load-fonts="false"
    regular-font="Consolas, monaco, monospace"
    mono-font="Consolas, monaco, monospace"
    :bg-color="theme.bg"
    :text-color="theme.text"
    :primary-color="theme.primary"
    class="h-full w-full"
  >
    <div slot="nav-logo">
	  <!-- custom component for added navigation -->
      <CoreNavigation slim hide-source class="pb-2" />
    </div>
  </rapi-doc>
<!-- [...] -->
```

**Comment by lrstanley** [comment]
Also an unrelated bug, but noticed this example:
https://rapidocweb.com/examples/themes.html#get-/pet/findByStatus

Has a broken method reference at the top of the reference:
![](https://cdn.liam.sh/share/2022/08/chrome_Whs37wDyId.png)

**Comment by mrin9** [comment]
w.r.t you original bug, where you need to click twice on nav-bar has already been taken care of, but not yet released.

if you like to test it at your end use `rapidoc-min.js` from `dist` folder in this repo
you also see it in action on our example page that uses non-released version https://rapidocweb.com/examples/focused-mode.html

The other bug where the method is repeated due to incorrect HTML is taken care by https://github.com/rapi-doc/RapiDoc/commit/ec5944a20aaf6b1be0bbdda5554e4e0f8d650d46
