### ISSUE TITLE
Feature request: `const` keyword support

### ISSUE THREAD

**Issue by ShadowLNC** [rapi-doc/RapiDoc#806]
If I do something like:

```yaml
get:
  responses:
    "200":
      content:
        application/json:
          schema:
            type: object
            properties:
              xyz:
                const: abc
```

I am hoping it can render the same as the following:

```yaml
xyz:
  type: string
  enum:
    - abc
```

In my case I'm also trying to use `const: ""` and empty strings don't render if they're the only value in an enum.

**Comment by mrin9** [comment]
The spec is a standardization defined by OpenAPI
We cannot change it or would like to interpret in any other way 

there is no `const` keyword support in the spec https://spec.openapis.org/oas/latest.html#properties 

however provide a minimal but complete spec per the standard where you have a single empty value for enum and letme check if that can be rendered

**Comment by ShadowLNC** [comment]
Thanks for the quick reply 😄 

Sorry - I was looking at [`const` in JSON Schema Validation](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-const).

I am a bit confused if JSON Schema Validation is supported as part of OpenAPI spec or only JSON Schema Core - things like `enum` ([examples in spec](https://spec.openapis.org/oas/latest.html#models-with-polymorphism-support)) seem to come from Validation but your link shows the spec only requiring Core (the section above your link contains links to both Core and Validation).

Here is a full example for the empty string as enum (I just replaced `abc` with an empty string and added the type since I am not sure if type is required for enum inference):

```yaml
openapi: 3.1.0
info:
  title: "Reproduction example"
  version: "2.0.0"
servers:
  - url: http://localhost:8000
    description: "Local Environment"

paths:
  /example:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  xyz:
                    type: string
                    enum:
                      - ""

security: []
```

**Comment by mrin9** [comment]
sorry for the confusion, I will take it back, you are correct, `const` is valid in JSON Schema draft 2020-12 and is therefore supported by OpenAPI 3.1 

at the moment support for this is missing in RapiDoc
but it is better to use enum with single value in order to be compatible with OpenAPI 3.0.3 or older 

aside that, coming to your specific issue;
when I tried the sample spec you provided in latest rapidoc beta it shows up like below

Example View
<img width="531" alt="image" src="https://user-images.githubusercontent.com/5056899/186550428-a6174e00-d132-4f9f-b026-2d8ccdfd869d.png">

Schema View
<img width="531" alt="image" src="https://user-images.githubusercontent.com/5056899/186550529-8db3b7db-18ac-41ea-a615-b72a3b50f292.png">

which IMO is correctly displaying. what is it you are expecting ?

**Comment by ShadowLNC** [comment]
In the Schema tab - if I have

```yaml
enum:
  - abc
```

Then it will say "Allowed values: abc" in the (multiline) description. If I have two enum values

```yaml
enum:
  - ""
  - abc
```

It will show "Allowed values: | abc".

When I use only empty string, it does not show allowed values (it is the same as your screenshot although I have a JSON object instead of tabular values - I assume this is new in the beta). I'm not sure how best to display an empty string but I am hoping it can be shown somehow 🙂

**Comment by mrin9** [comment]
let me check how best it can it be addressed as a quickfix
