### ISSUE TITLE
Possible to change the json body through any event/hooks before hitting ajax call ?

### ISSUE THREAD

**Issue by nikitapatel029** [rapi-doc/RapiDoc#815]
Hey Team,

I have one requirement where I do have large json body for one of post request so thinking to take only few params from user through input text box and other params which is not required/or need static value will pass by my self so is there any way I can modify request body through programmatically ?

NOTE: HERE I will take few params input from user through textbox(like how query /path params showing) not by text area as normal user might not understand the json language, how to pass in text area and all) so before sending request I need to convert it in json body and need to pass in  payload, any possibility ?

Thanks in advance

**Comment by mrin9** [comment]
RapiDoc is a UI for OpenAPI spec. Our target users are API consumers so we expect them to understand API and its functioning in general. 

It is not a goal of RapiDoc to become a perfect client for your API, That should be done through a dedicated UI. RapiDoc do not even validate the inputs against the validation that you have specified in the OpenAPI spec, because then you you may not test how the API behaves if provided with a incorrect input.

**Comment by nikitapatel029** [comment]
Hey @mrin9 

Totally Agree with this. 

But in my case we are having a big "multi level json body" so as of now we are using textarea where we are displaying entire json body in Textarea where user can change rom there if they want(and this is working fine), except that is there any other way to give text input for few fields and other fields from json body we can pass with default value without showing them?.

**Comment by mrin9** [comment]
you  may provide multiple examples in your spec. each example can contain desired set of properties, which user can select and change
