### ISSUE TITLE
Possible to pass Requet payload throught text box?

### ISSUE THREAD

**Issue by nikitapatel029** [rapi-doc/RapiDoc#818]
Hey Team,

First of all We are really loving to use rapidoc for our product. Thank a lot for such a great support!

I was looking for something where we can just give text input to user and accordingly json request payload will pass in body(check attached image). Through Rapidoc we can achieve with text are but any possibility to showcase like this? 

![image](https://user-images.githubusercontent.com/100831301/188904543-6304ab0f-6846-48c1-9719-b11e982958fd.png)

**Comment by mrin9** [comment]
not sure about the ask.
 
- if your API accepts multiple `query, path or header parameters`  the input  is provided as a `text-box`
- if your API accepts a `requestBody` the input  is provided as a `text-area`

further to it if you have a request body which can accepts different shapes of data, you can always provide multiple examples in your spec, your end-user can select each example and can edit the needed fields value.

https://rapidocweb.com/examples/examples-multiple.html#post-/multiple-example-in-request-body

![image](https://user-images.githubusercontent.com/5056899/188941786-7ede36ad-1097-4f02-914b-470049c0f645.png)

**Comment by nikitapatel029** [comment]
yes that I checked. 
My question was Our API is accept as requestbody but we want to show input as text-box so is there any possibility ?

You can see attached image, where they have shown text input(left side) that will add as json request body in api(check right side-curl code) so it would be easy for non technical person to give input through textbox, as through text area they might miss comma or quotes and might not understand what's going wrong.

![image](https://user-images.githubusercontent.com/100831301/189023201-d8f7a04f-da1a-4011-b662-21c43db56e55.png)

**Comment by mrin9** [comment]
We have checked out the example, where you are expecting provide some sort of JSON editor for your users. Here is what we think of it

- Our UX team feels the JSON creator with the text-boxes is rather more confusing and difficult to operate with vs a plain text-box. 
- Even if we decide to provide a JSON creator, our input will be text-area based which is more natural and readable in many ways
- We do like to provide the user an ability to make mistakes in the input as it allows our testing users to test the APIs against incorrect value


I am sorry, we wont be heading to this direction as it contradicts one of our fundamental rule where we do not validate inputs to allow testing incorrect input. However we have added a question for our next user survey about having a JSON editor, let see how that plays out first.

I am gonna close this issue here, I hope you can align your requirements with our current goals
