### ISSUE TITLE
How to hide Api Key from client side using Github secrets?

### ISSUE THREAD

**Issue by AnastasiaStratienko** [rapi-doc/RapiDoc#840]
Hi! I'd like to know if it's possible to use Github secrets for open api in rapid api? I didn't find any opened or closed issues about this on rapi-doc.
**Describing the situation:** I have an OpenApi json file and for this file I have only one api key for all users. My task is to hide this api key inside the code from user side, so users could be able to invoke endpoints without entering the api key. One of the ways to hide api key is using Github secrets.  
**My question:** Is it possible to use Github secrets for OpenApi in rapid api library? And if it´s possible how the part of api key code should look like?

Thanks a lot, in advance.

**Comment by mrin9** [comment]
RapiDoc is a client side app, that works on browser and do not store passwords or API key or anything else for that matter. 

It however presents a UI , where the user can input the API key. which is passed over when accessing the APIs
If this is not desired, then you can hide the section of the UI that asks for API key using `allow-authentication='false'`

Now in order to provide the key programmatically, you can read this API key from anywhere, 
such as env variable, file, github-secrets, aws-secrets, Hashicorps vault etc,  
and then use RapiDoc's `setApiKey( securitySchemeId, token)` method to provide it, which then will be passed to the APIs for authorization
