### ISSUE TITLE
Display examples generated from schema along with examples explicitly specified in spec

### ISSUE THREAD

**Issue by adriansuarez** [rapi-doc/RapiDoc#950]
If no examples are specified for an API endpoint, then an example is generated from the schema. For request payloads, this is populated into the request field.

But if examples are specified in the OpenAPI spec, then these generated examples are omitted. I actually find the generated examples useful since they show all fields and it is easy to craft any kind of request payload starting from that. And the explicit examples are obviously useful because they show specific use cases.

It would be good if there was an option to include both the explicit and generated examples.

**Comment by mrin9** [comment]
We took a feedback on this. The general opinion is that many would like to have their fields empty so that they dont have to remove them before putting their own values. and if a pre-field example is needed then they can always provide in the spec.

This behavior retains both the abilities. thats is to start with blank fields or with filled ones. filling the examples always weather they are provided in the spec will take away the ability to have blank fields.
Additionally there can be optional parameters and the user would like to keep them empty.
