### ISSUE TITLE
Can't set nav-active-item-marker="colored-block" as default

### ISSUE THREAD

**Issue by ddorian** [rapi-doc/RapiDoc#961]
See demo https://jsfiddle.net/2mbakuh0/4/
Can't set it by default as an option in the HTML, only by clicking the button (probably after the page has loaded).

**Comment by ddorian** [comment]
Currently it works only if I set it in before-render:

```html
<script>
    const rapidocEl = document.getElementById('thedoc');
        rapidocEl.addEventListener('before-render', (e) => {
          document.getElementById('thedoc').setAttribute('nav-active-item-marker', 'colored-block')
        });
</script>
```

**Comment by mrin9** [comment]
refer to this [example](https://rapidocweb.com/examples/nav-item-with-method.html#get-/pet/-petId-) 
The reason it do not show up immediately because  the nav only highlights the focused item on the navbar, therefore after you change the  `nav-active-item-marker` click on one of the nav-item to get the focus and see the effect

**Comment by ShadowLNC** [comment]
@mrin9 I just encountered the same issue, I think this is a duplicate of #900 

If you declare `nav-active-item-marker="colored-block"` in the HTML, it seems like even when you click on a `nav-item`, it will still use the `left-bar` styling.

Currently the workaround is to use setAttribute() as shown (and then click on a `nav-item`).
