### ISSUE TITLE
In 'focused' view, components still show up all on one page, causes hang

### ISSUE THREAD

**Issue by jarohen** [rapi-doc/RapiDoc#999]
Hey there :wave: 

I've got a decent amount of components in my schema (~75), some of which are mutually recursive (no problem with the recursive rendering btw, works great :slightly_smiling_face:). Trouble is, when I select one component in the menu on the left, the UI hangs for ~10s trying to render them all.

Any way I can get these rendering one-to-a-page in 'focused' view? It seems like the operations go from all-on-one-page to one-to-a-page when I change the render mode from 'read' to 'focused', but the components don't?

Cheers!

James

**Comment by wparad** [comment]
I'm curious do other tools on https://openapi.tools/ also hang with your spec?

**Comment by jarohen** [comment]
Hey @wparad, I'll take a look :eyes: 

It's an [open-source spec](https://github.com/xtdb/xtdb/blob/2.x/http-server/src/main/resources/openapi.yaml), if that helps

James

**Comment by jarohen** [comment]
Other ones we've already tried:

* redoc has [no plans](https://github.com/Redocly/redoc/issues/134) to support it
* swagger-ui seems to barf on any recursive schemas

**Comment by jarohen** [comment]
[Elements](https://stoplight.io/open-source/elements) from that list looks like it does the job for us - cheers! :pray:

**Comment by mrin9** [comment]
there are few ways you may address the issue. The goal is to reduce the DOM creation on the browser for that you can use the following
- Use `focused` mode , it creates the least amount of DOM elements on the browser
- If you have large nested schemas use `schema-expand-level=1` this will to a lazy creation of DOM elements 

RapiDoc will dereference the OpenAPI spec if it contains `refs` inside it. but if you are dealing with a large spec. I would suggest 
- dereference it before using any dereferencing tool 
- if your spec is in `yaml` convert it before to `JSON`

These will save some processing time as well

RapiDoc do allow these operations to happen on the server-side so that the browser's performance is not affected. however then we aren't talking abt a free offering.
